### ISSUE TITLE
Check block does not overflow

### ISSUE THREAD

**Issue by FlorianHuc** [Consensys/linea-arithmetization#639]
Add a check post all transactions have been selected to ensure that the compressed size of the rlp encoded tx is smaller than the max L1 data size.

cf https://github.com/Consensys/zkevm-monorepo/blob/main/coordinator/core/src/main/kotlin/net/consensys/zkevm/ethereum/coordination/conflation/ConflationCalculatorByDataCompressed.kt

function:   override fun checkOverflow(blockCounters: BlockCounters).

If the block overflow, the last tx should be removed recursively until it does not overflow.

**Comment by fab-10** [comment]
the full RLP of the block is not available during the line counting, but only after the txs have been selected, so my idea to implement this is to extend the txselector plugin to add an hook to validate the block after the selection, and reject it in case the gnark compressed size is bigger than the configured value

**Comment by fab-10** [comment]
@FlorianHuc which is the max L1 data size?

**Comment by gbotrel** [comment]
@fab-10 note that calling `CanWrite` is not enough, because the block limit check was disabled perf @FlorianHuc request;
```
	if blockLen > bm.limit {
		// we should panic but logging / alerting is handled by the caller.
		// see https://github.com/Consensys/zkevm-monorepo/issues/2326#issuecomment-1923573005
		log.Warn("block size is larger than the blob limit. This should be checked by the coordinator, keeping the log for sanity", "block size", blockLen, "limit", bm.limit)
	}
```

Either we re-enable this check, or, the sequencer should call
```
EncodeBlock(rlpBlock) // re-encodes the RLP block into Linea format.
CompressedSize(re-encodedBlock)
```
and check the returned value. These functions are stateless and safe to call concurrently,  but if we want to call the exact same API as the Coordinator, then
```
beforeSize := Len()
Write(rlpBlock)
afterSize := Len()
Reset()
```
would do the trick, but it's not safe to call from concurrent threads since it modifies the state of the blob maker.

**Comment by gbotrel** [comment]
update: added `MaxCompressedBlockSize` and `MaxCompressedTxSize` [to the API](https://github.com/Consensys/zkevm-monorepo/pull/2872#issue-2220666554)
